FROM golang:1.24 as tester
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV E2E_BASE_URL=http://app:8080
CMD ["go", "test", "./test/e2e", "-count=1"]
